### ISSUE TITLE
Convert the language selector to a drop-down box

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#61]
From this:

![image](https://user-images.githubusercontent.com/17465872/161380233-07e9a1e2-de5c-43c9-9a46-ca1c2499f5f9.png)

to this:

![image](https://user-images.githubusercontent.com/17465872/161380343-da0d0394-883d-448f-becb-002b20e78680.png)

What do you think?

Thank you

**Comment by milotype** [comment]
I agree with @ovari.

Make a language drop-down list of (translated) languages, but place it into the website's menu as a separate item, for instance called "Languages". I'd suggest to **define a percentage** of translation, in order to define which languages are represented. IMO, translations should be at least 85 % translated in order to be considered. 

That way the `<nav class="col-12 d-flex justify-content-end language-navigation">` would be obsolete.

**Comment by danyeaw** [comment]
I would assume this is lower priority without more translations. I agree that a drop-down would be better in the future, but it doesn't really seem to be something we need immediately.

**Comment by milotype** [comment]
I agree about the current low priority.

But that's why I've proposed **Create 07-mulitingual.md #32** which would invite translators to translate the app and website, thus increasing the possibility of having more languages ...

And I still would suggest to implement my feature request **Automatically Select Locale for Users #62**, as well as placing a "Language" item into the website's menu for selecting languages.

I'm really sorry, but I'm not a programmer, so I can't help implementing it.

**Comment by ovari** [comment]
> IMO, translations should be at least 85 % translated in order to be considered.

Please show all translations even if they are below 85%.

Some reasons to provide translations at all percentages are:
* Some people may only translate the main page
* It provides positive feedback as translators can see their translations, which then encourages them to do more
* Other people can see translations and also provide translation

Thank you

**Comment by danyeaw** [comment]
Here are a few sites also using Jekyll that have dropdowns:

- https://ubuntu-mate.org - nice stylized selector to match the other links in the header
- https://f-droid.org - gray dropdown selector
- https://leo3418.github.io - translation logo dropdown

I'm kind of digging the translation logo as the dropdown button, what do others think?

**Comment by danyeaw** [comment]
Thanks for the input @ovari!

@amolenaar Since you created the original site style, do you have any input?

**Comment by milotype** [comment]
**Suggestion:**
if you make a dropdown box for the languages, I'd suggest to add a separate menu item at the bottom of the list with a link to https://hosted.weblate.org/engage/gaphor/, for inviting users to translate. The text could be "Help translating", or something like that. This is something I found at https://joinpeertube.org/ and I find it's a slick solution.
![language-menu](https://user-images.githubusercontent.com/43657314/232251736-d220cba5-ec31-476b-9f79-feebdb34768d.png)

As an alternative I'd suggest to at least add a paragraph about translating in Gaphor's Contribute webpage https://gaphor.org/contribute.

For intance: _Help translating Gaphor at [Hosted Weblate](https://hosted.weblate.org/engage/gaphor/)._

In order to do that, a new string `Help translating Gaphor at [Hosted Weblate](https://hosted.weblate.org/engage/gaphor/).` would have to be added to the translation file https://hosted.weblate.org/projects/gaphor/gaphor-github-io/.

**Comment by ovari** [comment]
`magyar` should be written with a lowercase  `m`.

@danyeaw can you please change `Magyar` to `magyar`?

Thank you

**Comment by danyeaw** [comment]
Hi @ovari, done!

**Comment by ovari** [comment]
@danyeaw can the list be sorted by language code
Does https://github.com/gaphor/gaphor.github.io/pull/126 need to be deleted?

Thank you

**Comment by ovari** [comment]
@danyeaw can you please merge https://github.com/gaphor/gaphor.github.io/pull/129 instead of https://github.com/gaphor/gaphor.github.io/pull/126 ?

Thank you
