### ISSUE TITLE
Append `en-US/` to the English edition of the website

### ISSUE THREAD

**Issue by ovari** [gaphor/gaphor.github.io#67]
Instead of showing https://gaphor.org/ when visiting the English version of the Gaphor website, suggest changing this to https://gaphor.org/en-US/

In future, if https://gaphor.org/ is entered as the URL, that page would determine the locale on the visitors device and then automatically redirect to that locale. If that locale is currently not available on Gaphor, then the visitor would be redirected to https://gaphor.org/en-US/.

This is how https://www.thunderbird.net/ works. Please try it as see how to redirects to the current locale of your device.

The Thunderbird website code is available at https://github.com/thundernest/thunderbird-website if you would like to have a look.

What do you think?

Thank you

**Comment by danyeaw** [comment]
Hi @ovari, I understand #62, but why is it an advantage to make en-US a separate path?

**Comment by ovari** [comment]
> why is it an advantage to make en-US a separate path?

Convention seen at the Thunderbird website, i.e. https://www.thunderbird.net/ redirects to https://www.thunderbird.net/en-US/ if your system locale is en-US; otherwise it redirects to the locale setting of your system (if that locale is available).

Egalitarian as there is no favouritism (en-GB) (or favoritism (en-US)) for a specific language.

What do you think?

Thank you

**Comment by danyeaw** [comment]
This website is pretty different than how thunderbird's is setup for simplicity. They have a custom hosted website on Linode using mostly custom Python code. We have out of the box Jeykll using GitHub Pages. Jeykll is expecting to have a single website at /.

So I can see an argument for some additional egalitarian view, but from a pure user experience, why does it matter that a version exists at / instead of /en-US?
